#ifndef MATERIAL_TYPE_DEFINES_HLSLI
#define MATERIAL_TYPE_DEFINES_HLSLI

static const uint MATERIAL_TYPE_DIFFUSE_FACTOR = 0;
static const uint MATERIAL_TYPE_DIFFUSE_FACTOR_MAP = 1;
static const uint MATERIAL_TYPE_DIFFUSE_COLOR = 2;
static const uint MATERIAL_TYPE_DIFFUSE_COLOR_MAP = 3;
static const uint MATERIAL_TYPE_SPECULAR_FACTOR = 4;
static const uint MATERIAL_TYPE_SPECULAR_FACTOR_MAP = 5;
static const uint MATERIAL_TYPE_SPECULAR_COLOR = 6;
static const uint MATERIAL_TYPE_SPECULAR_COLOR_MAP = 7;
static const uint MATERIAL_TYPE_SPECULAR_EXPONENT = 8;
static const uint MATERIAL_TYPE_SPECULAR_EXPONENT_MAP = 9;
static const uint MATERIAL_TYPE_REFLECTION_FACTOR = 10;
static const uint MATERIAL_TYPE_REFLECTION_FACTOR_MAP = 11;
static const uint MATERIAL_TYPE_REFLECTION_COLOR = 12;
static const uint MATERIAL_TYPE_REFLECTION_COLOR_MAP = 13;
static const uint MATERIAL_TYPE_TRANSPARENCY_FACTOR = 14;
static const uint MATERIAL_TYPE_TRANSPARENCY_FACTOR_MAP = 15;
static const uint MATERIAL_TYPE_TRANSPARENCY_COLOR = 16;
static const uint MATERIAL_TYPE_TRANSPARENCY_COLOR_MAP = 17;
static const uint MATERIAL_TYPE_EMISSION_FACTOR = 18;
static const uint MATERIAL_TYPE_EMISSION_FACTOR_MAP = 19;
static const uint MATERIAL_TYPE_EMISSION_COLOR = 20;
static const uint MATERIAL_TYPE_EMISSION_COLOR_MAP = 21;
static const uint MATERIAL_TYPE_AMBIENT_FACTOR = 22;
static const uint MATERIAL_TYPE_AMBIENT_FACTOR_MAP = 23;
static const uint MATERIAL_TYPE_AMBIENT_COLOR = 24;
static const uint MATERIAL_TYPE_AMBIENT_COLOR_MAP = 25;
static const uint MATERIAL_TYPE_NORMAL_MAP = 26;
static const uint MATERIAL_TYPE_NORMAL_MAP_MAP = 27;
static const uint MATERIAL_TYPE_BUMP = 28;
static const uint MATERIAL_TYPE_BUMP_MAP = 29;
static const uint MATERIAL_TYPE_BUMP_FACTOR = 30;
static const uint MATERIAL_TYPE_BUMP_FACTOR_MAP = 31;
static const uint MATERIAL_TYPE_DISPLACEMENT_FACTOR = 32;
static const uint MATERIAL_TYPE_DISPLACEMENT_FACTOR_MAP = 33;
static const uint MATERIAL_TYPE_DISPLACEMENT = 34;
static const uint MATERIAL_TYPE_DISPLACEMENT_MAP = 35;
static const uint MATERIAL_TYPE_VECTOR_DISPLACEMENT_FACTOR = 36;
static const uint MATERIAL_TYPE_VECTOR_DISPLACEMENT_FACTOR_MAP = 37;
static const uint MATERIAL_TYPE_VECTOR_DISPLACEMENT = 38;
static const uint MATERIAL_TYPE_VECTOR_DISPLACEMENT_MAP = 39;

static const uint MATERIAL_FIELD_COUNT = 40;

#endif
