#ifndef MATERIAL_TYPE_DEFINES_HLSLI
#define MATERIAL_TYPE_DEFINES_HLSLI

static const uint MATERIAL_TYPE_SHADING_MODEL = 0;
static const uint MATERIAL_TYPE_TWO_SIDED = 1;
static const uint MATERIAL_TYPE_WIREFRAME = 2;
static const uint MATERIAL_TYPE_BLEND_MODE = 3;
static const uint MATERIAL_TYPE_OPACITY = 4;
static const uint MATERIAL_TYPE_ALPHA_MODE = 5;
static const uint MATERIAL_TYPE_ALPHA_CUTOFF = 6;
static const uint MATERIAL_TYPE_BASE_COLOR = 7;
static const uint MATERIAL_TYPE_DIFFUSE_COLOR = 8;
static const uint MATERIAL_TYPE_AMBIENT_COLOR = 9;
static const uint MATERIAL_TYPE_SPECULAR_COLOR = 10;
static const uint MATERIAL_TYPE_EMISSIVE_COLOR = 11;
static const uint MATERIAL_TYPE_TRANSPARENT_COLOR = 12;
static const uint MATERIAL_TYPE_REFLECTIVE_COLOR = 13;
static const uint MATERIAL_TYPE_METALLIC_FACTOR = 14;
static const uint MATERIAL_TYPE_ROUGHNESS_FACTOR = 15;
static const uint MATERIAL_TYPE_NORMAL_SCALE = 16;
static const uint MATERIAL_TYPE_OCCLUSION_STRENGTH = 17;
static const uint MATERIAL_TYPE_EMISSIVE_STRENGTH = 18;
static const uint MATERIAL_TYPE_DIFFUSE_TEXTURE = 19;
static const uint MATERIAL_TYPE_SPECULAR_TEXTURE = 20;
static const uint MATERIAL_TYPE_AMBIENT_TEXTURE = 21;
static const uint MATERIAL_TYPE_EMISSIVE_TEXTURE = 22;
static const uint MATERIAL_TYPE_OPACITY_TEXTURE = 23;
static const uint MATERIAL_TYPE_SHININESS_TEXTURE = 24;
static const uint MATERIAL_TYPE_HEIGHT_BUMP_TEXTURE = 25;
static const uint MATERIAL_TYPE_NORMAL_TEXTURE = 26;
static const uint MATERIAL_TYPE_DISPLACEMENT_TEXTURE = 27;
static const uint MATERIAL_TYPE_REFLECTION_TEXTURE = 28;
static const uint MATERIAL_TYPE_LIGHTMAP_TEXTURE = 29;

static const uint MATERIAL_FIELD_COUNT = 30;

#endif
